# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "de8f386e5474bdc1fb1e50af80f97b08"
application_url = "https://example.com/"
embedded = true
name = "KFO Order Management"
handle = "kfo-order-management-1"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_checkouts,read_customers,read_discounts,read_draft_orders,read_fulfillments,read_inventory,read_locations,read_merchant_managed_fulfillment_orders,read_metaobject_definitions,read_metaobjects,read_order_edits,read_orders,read_products,read_returns,read_shipping,read_third_party_fulfillment_orders,write_assigned_fulfillment_orders,write_checkouts,write_customers,write_discounts,write_draft_orders,write_fulfillments,write_inventory,write_merchant_managed_fulfillment_orders,write_metaobject_definitions,write_metaobjects,write_order_edits,write_orders,write_products,write_returns,write_shipping,write_third_party_fulfillment_orders"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[pos]
embedded = false

[build]
include_config_on_deploy = true
